name: 'Terraform VM Workflow'
'on': push
jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}


    steps:
      - name: Check code
        uses: actions/checkout@v2

      - name: Create directory "terraform"
        run: 
          mkdir -p terraform

      - name: List files in the working directory
        run: 
          ls -R

      - name: Download Terraform state
        uses: actions/download-artifact@v4
        with: 
          name: terraform-state
          path: ./terraform/
        continue-on-error: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: 1.0.0
      
      - name: Azure Login
        uses: azure/login@v1
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS_VALUES }}'

      - name: Terraform Init
        run: terraform init -backend-config="storage_account_name=gitactionsstatekbtest"  -backend-config="container_name=github-actions-state"   -backend-config="key=vm_provisioning/terraform.tfstate" -backend-config="resource_group_name=github-actions-resources" -backend-config="secrets\sp.tfvars"

      - name: Terraform format
        run: terraform fmt

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve


      - name: List all files in working directory
        run: ls -R

      - name: Upload Terraform state
        uses: actions/upload-artifact@v4        
        with:
          name: terraform-state
          path: ./terraform/terraform.tfstate