name: 'Terraform VM Workflow'
'on': push
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Check code
        uses: actions/checkout@v2

      - name: Download Terraform state
        uses: actions/download-artifact@v2
        with: 
          name: terraform-state
          path: ./terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: 1.0.0
      
      - name: Azure Login
        uses: azure/login@v1
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS_VALUES }}'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var 'azure_credentials=${{ secrets.AZURE_CREDENTIALS_VALUES }}'

      - name: Terraform Apply
        run: terraform apply -auto-approve -var 'azure_credentials=${{ secrets.AZURE_CREDENTIALS_VALUES }}'

      - name: Upload Terrzform state
        uses: actions/upload-artifact@v2
        with:
          name: terraform-state
          path: ./terraform/terraform.state