name: Terraform test Workflow
on: 
  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}

    steps:
      - name: Check code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: 1.0.0
      
      - name: Azure Login
        uses: azure/login@v1
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS_VALUES }}'

      - name: Terraform Init
        use: hashicorp/terraform-github-actions/init@0.4.0
        
      - name: Terraform format
        run: terraform fmt

      - name: Terraform Plan
        run: terraform plan  -var-file='secrets/sp.tfvars'

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="secrets/sp.tfvars"



